import React, { useState } from 'react';
import { Model3DSpec } from '../types';
import { Download, FileCode, Camera, Check, Copy, Box } from 'lucide-react';

interface ExportModalProps {
  model: Model3DSpec;
  isOpen: boolean;
  onClose: () => void;
  onExportGLTF: () => void;
  onExportOBJ: () => void;
  onExportSTL: () => void;
  onCapturePNG: () => string | null;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  model,
  isOpen,
  onClose,
  onExportGLTF,
  onExportOBJ,
  onExportSTL,
  onCapturePNG,
}) => {
  const [copiedCode, setCopiedCode] = useState(false);
  const [snapshotUrl, setSnapshotUrl] = useState<string | null>(null);

  if (!isOpen) return null;

  // Generate Three.js React TS code representation
  const generateCodeSnippet = () => {
    return `// Three.js JSX Model Component - Generated by 3D Minimal Studio (Google AI Studio)
import React from 'react';
import * as THREE from 'three';

export function Model3D(props) {
  return (
    <group {...props}>
${model.parts
  .map(
    (p) => `      {/* ${p.name} */}
      <mesh position={[${p.position.join(', ')}]} rotation={[${p.rotation.join(', ')}]} scale={[${p.scale.join(', ')}]}>
        <${p.shape === 'box' ? 'boxGeometry' : p.shape === 'sphere' ? 'sphereGeometry' : 'cylinderGeometry'} args={[1, 1, 1]} />
        <meshStandardMaterial color="${p.color}" metalness={${p.metalness}} roughness={${p.roughness}} ${p.emissive ? `emissive="${p.emissive}" emissiveIntensity={${p.emissiveIntensity || 0.5}}` : ''} />
      </mesh>`
  )
  .join('\n')}
    </group>
  );
}`;
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(generateCodeSnippet());
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  const handleTakeSnapshot = () => {
    const url = onCapturePNG();
    if (url) {
      setSnapshotUrl(url);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-md flex items-center justify-center p-4 z-50">
      <div className="bg-[#121317] border border-[#232630] w-full max-w-2xl rounded-2xl shadow-2xl overflow-hidden flex flex-col text-white max-h-[90vh]">
        {/* Header */}
        <div className="p-4 border-b border-[#232630] bg-[#16181f] flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Download className="w-5 h-5 text-[#00FF66]" />
            <h2 className="text-sm font-semibold tracking-wider uppercase text-gray-200">ส่งออกโมเดล 3D (Export & Download)</h2>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-white text-sm p-1 rounded-lg hover:bg-[#20232e]"
          >
            ✕
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-6 text-xs custom-scrollbar">
          {/* File Formats Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {/* GLTF / GLB */}
            <div className="bg-[#181a22] border border-[#272b38] p-4 rounded-xl flex flex-col justify-between space-y-3">
              <div>
                <span className="font-bold text-sm text-[#00FF66] block">GLTF / GLB Model</span>
                <p className="text-gray-400 text-[11px] mt-1">ไฟล์มาตรฐาน WebGL, Blender, Unity, Unreal</p>
              </div>
              <button
                onClick={onExportGLTF}
                className="bg-[#00FF66] hover:bg-[#00E676] text-black font-semibold py-2 px-3 rounded-lg flex items-center justify-center gap-2 shadow-md shadow-[#00FF66]/20 transition-all cursor-pointer text-xs"
              >
                <Download className="w-3.5 h-3.5" />
                <span>ดาวน์โหลด .GLTF</span>
              </button>
            </div>

            {/* OBJ Mesh */}
            <div className="bg-[#181a22] border border-[#272b38] p-4 rounded-xl flex flex-col justify-between space-y-3">
              <div>
                <span className="font-bold text-sm text-white block">OBJ Wavefront</span>
                <p className="text-gray-400 text-[11px] mt-1">ไฟล์ 3D เรขาคณิตมาตรฐาน Maya, ZBrush</p>
              </div>
              <button
                onClick={onExportOBJ}
                className="bg-[#212532] hover:bg-[#2d3244] border border-[#3b4257] text-white font-semibold py-2 px-3 rounded-lg flex items-center justify-center gap-2 transition-all cursor-pointer text-xs"
              >
                <Box className="w-3.5 h-3.5 text-[#00FF66]" />
                <span>ดาวน์โหลด .OBJ</span>
              </button>
            </div>

            {/* STL 3D Print */}
            <div className="bg-[#181a22] border border-[#272b38] p-4 rounded-xl flex flex-col justify-between space-y-3">
              <div>
                <span className="font-bold text-sm text-white block">STL 3D Printing</span>
                <p className="text-gray-400 text-[11px] mt-1">ไฟล์สำหรับพิมพ์ 3D Printer, AutoCAD, SolidWorks</p>
              </div>
              <button
                onClick={onExportSTL}
                className="bg-[#212532] hover:bg-[#2d3244] border border-[#3b4257] text-white font-semibold py-2 px-3 rounded-lg flex items-center justify-center gap-2 transition-all cursor-pointer text-xs"
              >
                <Download className="w-3.5 h-3.5 text-[#00FF66]" />
                <span>ดาวน์โหลด .STL</span>
              </button>
            </div>
          </div>

          {/* High-Res Snapshot Render */}
          <div className="bg-[#181a22] border border-[#272b38] p-4 rounded-xl space-y-3">
            <div className="flex items-center justify-between">
              <div>
                <span className="font-bold text-sm text-white block">ภาพแคปเจอร์ความละเอียดสูง (PNG Snapshot)</span>
                <p className="text-gray-400 text-[11px] mt-0.5">บันทึกภาพมุมมองปัจจุบันเป็นไฟล์ PNG พื้นหลังคมชัด</p>
              </div>
              <button
                onClick={handleTakeSnapshot}
                className="bg-[#212532] hover:bg-[#2d3244] text-[#00FF66] border border-[#00FF66]/30 font-semibold py-1.5 px-3 rounded-lg flex items-center gap-1.5 cursor-pointer"
              >
                <Camera className="w-4 h-4" />
                <span>ถ่ายภาพ</span>
              </button>
            </div>

            {snapshotUrl && (
              <div className="mt-3 space-y-2 border-t border-[#272b38] pt-3">
                <img
                  src={snapshotUrl}
                  alt="3D Snapshot"
                  className="w-full h-40 object-contain bg-[#0b0c0e] rounded-lg border border-[#272b38]"
                />
                <a
                  href={snapshotUrl}
                  download={`${model.title.toLowerCase().replace(/\s+/g, '-')}-snapshot.png`}
                  className="inline-flex items-center gap-1.5 text-xs text-[#00FF66] font-medium hover:underline"
                >
                  <Download className="w-3.5 h-3.5" /> บันทึกรูปภาพลงเครื่อง
                </a>
              </div>
            )}
          </div>

          {/* React Three.js Code Export */}
          <div className="bg-[#181a22] border border-[#272b38] p-4 rounded-xl space-y-3">
            <div className="flex items-center justify-between">
              <span className="font-bold text-sm text-white flex items-center gap-2">
                <FileCode className="w-4 h-4 text-[#00FF66]" /> โค้ด Three.js React Component
              </span>
              <button
                onClick={handleCopyCode}
                className="bg-[#212532] hover:bg-[#00FF66] text-gray-300 hover:text-black border border-[#3b4257] font-semibold py-1 px-2.5 rounded-lg flex items-center gap-1.5 cursor-pointer transition-all text-[11px]"
              >
                {copiedCode ? <Check className="w-3.5 h-3.5 text-black" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedCode ? 'คัดลอกเรียบร้อย!' : 'คัดลอกโค้ด'}</span>
              </button>
            </div>

            <pre className="bg-[#0b0c0e] p-3 rounded-lg border border-[#232630] font-mono text-[11px] text-gray-300 overflow-x-auto max-h-44 custom-scrollbar">
              {generateCodeSnippet()}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
};
